### ISSUE TITLE
Enchanting treasures in ZC suddenly showing on map again

### ISSUE THREAD

**Issue by nozzlegear** [kemayo/wow-handynotes-dragonflight#30]
Hey! I'm having a strange problem with Handynotes that I suspect is actually an issue with the game's API itself, but wanted to file an issue here to confirm. I used Handynotes to collect the three new enchanting treasures in Zaralek Caverns, but recently they all showed up on the map again and won't go away. I've confirmed that none of the treasures are actually there where the map says they are.

If I take the quest ids from the [Enchanting.lua file](https://github.com/kemayo/wow-handynotes-dragonflight/blob/c23448a6f8a81f0854e53336f76ea788b3c6b07e/profession_knowledge/Enchanting.lua#L80) and check them using `C_QuestLog.IsQuestFlaggedCompleted`, all three return false: 

```lua
print(C_QuestLog.IsQuestFlaggedCompleted(204990)) -- false
print(C_QuestLog.IsQuestFlaggedCompleted(205001)) -- false
print(C_QuestLog.IsQuestFlaggedCompleted(204999)) -- false
```

So again I think it's probably an issue with Blizzard but just wanted to check and see if I'm misunderstanding what Handynotes is doing?

**Comment by kemayo** [comment]
The questids weren't present yet, which is why those checks were returning false -- you were trying it with the itemids of the rewards. That said, chris-merritt has provided all these questids now, which have merged in e1e8f79f7091e9ddd9a185c15e42d6e83349743f, so a release I'll put out shortly should fix this..
